// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('approve_Crime', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('approve_Crime', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 872, height: 691 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("202412118@dau.ac.in")
    await driver.findElement(By.id("password")).sendKeys("vpt@2036")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).click()
    {
      const element = await driver.findElement(By.id("password"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Vpt@2036")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).click()
    {
      const element = await driver.findElement(By.id("email"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("202412004@dau.ac.in")
    await driver.findElement(By.id("password")).sendKeys("vpt@2036")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".leaflet-marker-icon")).click()
    await driver.findElement(By.css(".focus\\3Aring-1")).click()
    await driver.findElement(By.css(".focus\\3Aring-1")).sendKeys("veified as proofs are valid")
    await driver.findElement(By.css(".bg-green-600")).click()
  })
})
