// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ReportCrime', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('ReportCrime', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.id("email")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".px-3")).click()
    vars["win800"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win800"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("202412093@dau.ac.in")
    await driver.findElement(By.id("password")).sendKeys("Vpt@2036")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("password")).sendKeys("vpt@2036")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("Report Crime")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("Rickshaw theft")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("rickshaw stolen from my sockeity parking ")
    await driver.findElement(By.css(".leaflet-container")).click()
    await driver.findElement(By.id("datetime")).click()
    await driver.findElement(By.id("datetime")).click()
    await driver.findElement(By.id("datetime")).click()
    await driver.findElement(By.id("datetime")).click()
    await driver.findElement(By.id("datetime")).click()
    await driver.findElement(By.css(".relative > div:nth-child(2)")).click()
    await driver.findElement(By.id("datetime")).click()
    await driver.findElement(By.id("datetime")).sendKeys("2025-11-30T12:12")
    await driver.findElement(By.css(".mt-2:nth-child(2)")).click()
    await driver.findElement(By.css(".mt-2:nth-child(2)")).sendKeys("C:\\fakepath\\Flyer-01 (1).jpg")
    await driver.findElement(By.id("anonymous")).click()
    await driver.findElement(By.css(".bg-blue-600")).click()
    await driver.findElement(By.css(".MuiBackdrop-root:nth-child(3)")).click()
    await driver.findElement(By.linkText("View Reported Crimes")).click()
  })
})
