// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SignUp_Email', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SignUp_Email', async function() {
    // Test name: SignUp_Email
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://kavach-frontend-ten.vercel.app/")
    // 2 | setWindowSize | 1550x830 | 
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    // 3 | click | linkText=Register here | 
    await driver.findElement(By.linkText("Register here")).click()
    // 4 | click | id=name | 
    await driver.findElement(By.id("name")).click()
    // 5 | type | id=name | Kalrav
    await driver.findElement(By.id("name")).sendKeys("Kalrav")
    // 6 | type | id=email | kalravjkapadia@gmail.com
    await driver.findElement(By.id("email")).sendKeys("kalravjkapadia@gmail.com")
    // 7 | type | id=password | UggaBooga@123
    await driver.findElement(By.id("password")).sendKeys("UggaBooga@123")
    // 8 | click | css=.bg-blue-600 | 
    await driver.findElement(By.css(".bg-blue-600")).click()
  })
})
