// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('viewLogs_filters', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('viewLogs_filters', async function() {
    await driver.get("http://localhost:3000/super-admin/home")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.linkText("View Logs")).click()
    await driver.findElement(By.name("action")).click()
    await driver.findElement(By.css(".p-6")).click()
    {
      const element = await driver.findElement(By.name("userRole"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.name("userRole"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.name("userRole"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.name("userRole")).click()
    {
      const dropdown = await driver.findElement(By.name("userRole"))
      await dropdown.findElement(By.xpath("//option[. = 'Public']")).click()
    }
    await driver.findElement(By.css("option:nth-child(2)")).click()
    await driver.findElement(By.name("startDate")).click()
    await driver.findElement(By.name("startDate")).click()
    await driver.findElement(By.name("startDate")).click()
    await driver.findElement(By.name("startDate")).click()
    await driver.findElement(By.name("startDate")).sendKeys("2025-12-08")
    await driver.findElement(By.name("endDate")).click()
    await driver.findElement(By.name("endDate")).sendKeys("2025-12-13")
    await driver.findElement(By.css(".bg-blue-600")).click()
  })
})
