// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('navbar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('navbar', async function() {
    await driver.get("http://localhost:3000/super-admin/home")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.linkText("Manage Admins")).click()
    await driver.findElement(By.linkText("Manage Users")).click()
    await driver.findElement(By.linkText("View Logs")).click()
    await driver.findElement(By.linkText("Verified Crimes")).click()
  })
})
