// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SignIn_OAuth', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('SignIn_OAuth', async function() {
    await driver.get("https://kavach-frontend-ten.vercel.app/")
    await driver.manage().window().setRect({ width: 842, height: 696 })
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".px-3")).click()
    vars["win6926"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win6926"])
    await driver.findElement(By.id("identifierId")).sendKeys("kalravjkapadia@gmail.com")
    await driver.findElement(By.id("identifierId")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".WpHeLc")).click()
    await driver.findElement(By.id("identifierId")).sendKeys("kalravjkapadia@gmail.com")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click()
    await driver.findElement(By.name("Passwd")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("UoogaBooga@123")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.close()
    await driver.switchTo().window(vars["root"])
  })
})
