// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SignIn_Email', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SignIn_Email', async function() {
    await driver.get("https://kavach-frontend-ten.vercel.app/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("kalravjkapadia@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("UoogaBooga@123")
    await driver.findElement(By.css(".bg-blue-600")).click()
  })
})
