// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('manageUser', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('manageUser', async function() {
    await driver.get("http://localhost:3000/super-admin/home")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.linkText("Manage Users")).click()
    await driver.findElement(By.css(".border-b:nth-child(1) .px-3")).click()
    await driver.findElement(By.css(".px-4:nth-child(2)")).click()
    await driver.findElement(By.css(".px-4:nth-child(2)")).click()
    await driver.findElement(By.css(".px-4:nth-child(2)")).click()
    await driver.findElement(By.css(".border:nth-child(1) > .text-sm:nth-child(3)")).click()
    await driver.findElement(By.css(".border:nth-child(1) > .text-sm:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css(".border:nth-child(1) > .text-sm:nth-child(3)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".bg-gray-200")).click()
  })
})
