// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('manageAdmins', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('manageAdmins', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".px-3")).click()
    vars["win1521"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win1521"])
    await driver.findElement(By.id("identifierId")).click()
    await driver.findElement(By.id("identifierId")).sendKeys("202412033@dau.ac.in")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("Kalrav@da@123")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("Kalrav@da@704")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("Kalrav@da@1234")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("Kalrav@da@123")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.findElement(By.name("Passwd")).sendKeys("Kalrav@da@704")
    await driver.findElement(By.css(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).click()
    await driver.close()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("rahul.megascale@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Vpt@2036")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("Manage Admins")).click()
    await driver.findElement(By.css(".flex:nth-child(1) .PrivateSwitchBase-input")).click()
    await driver.findElement(By.linkText("Manage Users")).click()
  })
})
